markdown            : kramdown
theme               : minima
name                : Fabio's homepage
description         : Bookmark this to keep an eye on my project updates!
timezone            : Europe/Rome
